### ISSUE TITLE
请问用什么 IDE 开发的？

### ISSUE THREAD

**Issue by pexcn** [kaneawk/shadowsocksr-android#1]
请问这种用 Scala 写的 Android 应用程序是用什么 IDE 开发的？还是用 Vim 或者 Emacs 呢？

**Comment by kaneawk** [comment]
IDE is not important, you can try idea+sbt.

**Comment by pexcn** [comment]
1. 请问您是用什么工具的呢？
2. 另外我想知道如何自动导包和语法提示，是不是 vim 安装插件就可以了？

**Comment by kaneawk** [comment]
You can ask madeye: https://github.com/shadowsocks/shadowsocks-android

**Comment by pexcn** [comment]
@kaneawk 我问过了，但是没回复我。您是用什么工具开发这个 shadowsocksr 的 android 版的呢？

**Comment by kaneawk** [comment]
https://www.jetbrains.com/idea/

**Comment by pexcn** [comment]
好吧，用的 Scala 插件？
