### ISSUE TITLE
android协议转换  

### ISSUE THREAD

**Issue by Heappys** [kaneawk/shadowsocksr-android#8]
协议转换这个功能什么时候增加？

**Comment by kaneawk** [comment]
这是什么功能？

**Comment by Heappys** [comment]
协议转换，把UDP包封装于TCP里发送，或把TCP包封装于UDP里发送

**Comment by kaneawk** [comment]
发 issue 向这个分支。
https://github.com/shadowsocksr/shadowsocksr-android
